name: "dbt_project"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_project"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbt_project:
    staging:
      +materialized: view
      +database: DEV
    intermediate:
      +materialized: table
      +database: REFINED

seeds:
  dbt_project:
    +materialized: seed
    +database: REFINED
    +schema: MANUAL_SOURCES

snapshots:
  dbt_project:
    +database: DEV
    +snapshot_meta_column_names:
      dbt_valid_from: record_effective_start_timestamp
      dbt_valid_to: record_effective_end_timestamp
      dbt_scd_id: dbt_id
      dbt_updated_at: dbt_updated_at
      dbt_is_deleted: is_deleted